import { Option } from '@ephox/katamari';
declare const _default: {
    getBody: (editor: any) => any;
    getDoc: (editor: any) => any;
    getWin: (editor: any) => any;
    getSelection: (editor: any) => any;
    getFrame: (editor: any) => any;
    getActiveApi: (editor: any) => Option<{
        body: any;
        doc: any;
        win: any;
        html: any;
        getSelection: any;
        setSelection: any;
        clearSelection: any;
        frame: any;
        onKeyup: any;
        onNodeChanged: any;
        onDomChanged: any;
        onScrollToCursor: any;
        onScrollToElement: any;
        onToReading: any;
        onToEditing: any;
        onToolbarScrollStart: any;
        onTouchContent: any;
        onTapContent: any;
        onTouchToolstrip: any;
        getCursorBox: any;
    }>;
};
export default _default;
