declare const _default: {
    opera: any;
    webkit: any;
    ie: any;
    gecko: any;
    mac: any;
    iOS: any;
    android: any;
    contentEditable: any;
    transparentSrc: string;
    caretAfter: boolean;
    range: boolean;
    documentMode: any;
    fileApi: any;
    ceFalse: boolean;
    cacheSuffix: string;
    container: any;
    overrideViewPort: any;
    experimentalShadowDom: boolean;
    canHaveCSP: boolean;
    desktop: boolean;
    windowsPhone: any;
};
export default _default;
