import { CaretPosition } from 'tinymce/core/caret/CaretPosition';
declare const isCaretContainerBlock: (node: Node) => boolean;
declare const isCaretContainerInline: (node: Node) => boolean;
declare const isCaretContainer: (node: Node) => boolean;
declare const hasContent: (node: Node) => boolean;
declare const insertInline: (node: Node, before: boolean) => Node;
declare const prependInline: (node: Node) => Node;
declare const appendInline: (node: Node) => Node;
declare const isBeforeInline: (pos: CaretPosition) => boolean;
declare const isAfterInline: (pos: CaretPosition) => boolean;
declare const insertBlock: (blockName: string, node: Node, before: boolean) => Node;
declare const startsWithCaretContainer: (node: Node) => boolean;
declare const endsWithCaretContainer: (node: Node) => boolean;
declare const showCaretContainerBlock: (caretContainer: Element) => Element;
declare const isRangeInCaretContainerBlock: (range: Range) => boolean;
export { isCaretContainer, isCaretContainerBlock, isCaretContainerInline, showCaretContainerBlock, insertInline, prependInline, appendInline, isBeforeInline, isAfterInline, insertBlock, hasContent, startsWithCaretContainer, endsWithCaretContainer, isRangeInCaretContainerBlock };
